### ISSUE TITLE
Update flags for WPCS 2.0.0

### ISSUE THREAD

**Issue by ajaydsouza** [claudiosanches/vscode-wpcs-whitelist-flags#1]
The WPCS flags are deprecated in WPCS 2.0.0 and will be removed in WPCS 3.0.0

https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/wiki/Whitelisting-code-which-flags-errors

Will you be updating this to use the PHPCS format (// phpcs:ignore) which is now the preferred format.

**Comment by claudiosanches** [comment]
Yes, I'm going to update.

**Comment by claudiosanches** [comment]
Closed by #2
